#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# We would normaly not expose this and store it in an .env or the local.properties but this key only has permissions to read github packages (in this case only forge) so I expose it for an easier setup
gpr.user=48493983
gpr.key=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