org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true

# We would normaly not expose this and store it in an .env or the local.properties but this key only has permissions to read github packages (in this case only forge) so I expose it for an easier setup
gpr.user=48493983
gpr.key=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